app:
  name: "web_app"
  mode: "release"
  port: 8081
log:
    level: "debug"
    filename: "web_app_log.log"
    max_size: 200
    max_age: 30
    max_backups: 7
mysql:
  host: "127.0.0.1"
  user: root
  password: 142212
  port: 3306
  dbname: "sqk_demo"
  max_conn: 200
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  poolsize: 100